---
- name: Define Istio hash as fact.
  set_fact:
     __i: "{{ istio_defaults | combine(istio, recursive=True) }}"

- name: Get Istio bundle.
  include: get_istio.yml

- name: Set path to 'oc'
  include: set_oc.yml

- name: Login to active Minishift instance.
  include: login.yml

- name: Clean previous Istio installation.
  include: clean.yml
  when: __i.action_to_trigger == 'clean'

- name: Deploy Weave Scope
  include: deploy_weave_scope.yml
  when: __i.action_to_trigger == 'deploy'

- name: Deploy Istio, Addons and Bookinfo App.
  include: deploy.yml
  when: __i.action_to_trigger == 'deploy'
